version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: condomanage
    ports:
      - "5432:5432"
    #volumes:
    #  - ./app/data-files/postgres:/var/lib/postgresql/data # Persistência de dados
    networks:
    - my_local_network

networks:
  my_local_network:
    driver: bridge